 /*
 ============================================================================
 Name        : utn.c
 Author      : Gonzalo Sinnott Segura
 Version     :
 Copyright   :
 Description : Library ArrayEmployees.c
 ============================================================================
 */

#include <stdio_ext.h>
#include <stdlib.h>
#include <string.h>
#include "mi_biblioteca.h"
#include "ArrayEmployees.h"

static int generateNewId(void);
static int addEmployees(sEmployee* list,int len,int id,char name[],char lastName[],float salary,int sector,int index);


/* \brief initEmployees: To indicate that all positions in the array are empty,
 * this function put the flag (isEmpty) in TRUE in all position of the array
 * \param sEmployee* list: Pointer to array of employees
 * \param int len: Array length
 * \return (-1) Error / (0) Ok
 */

int initEmployees(sEmployee* list, int len)
{
	int retorno = -1;
	if(list != NULL && len > 0)
	{
		for(int i=0;i<len;i++)
		{
			list[i].isEmpty = TRUE;
		}
		retorno = 0;
	}
	return retorno;
}


/* \brief checkFirstEmptyIndex: Checks first empty index in the array
 * this function search the array for the first index with the value TRUE in the isEmpty item
 * \param sEmployee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int *EmptyIndex: Pointer to position of first empty index.
 * \return (-1) Error / (0) Ok
 */

int checkFirstEmptyIndex(sEmployee* list, int len, int *emptyIndex)
{
	int retornar = -1;
	if(list != NULL && len >0 && emptyIndex != NULL)
	{
		for(int i = 0; i < len; i++)
		{
			if(list[i].isEmpty == TRUE)
			{
				*emptyIndex = i;
				retornar = 0;
				break;
			}
		}
	}
	return retornar;
}

/* \brief loadEmployeeData: Asks the user for the employee data
 * \param sEmployee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int: *emptyIndex Pointer to position of first empty index.
 * \return (-1) Error / (0) Ok
 */

int loadEmployeeData(sEmployee* list,int len, int index)
{
	int retorno = -1;
    int id;
    char name[LONG_NAME];
    char lastName[LONG_NAME];
    float salary;
    int sector;


    if(list != NULL && len > 0 && index >= 0 && index < len)
    {
        id=generateNewId();
        utn_getString("Ingrese Apellido:", "\nError. ", lastName, 3, LONG_NAME);
        utn_getString("Ingrese Nombre:", "\nError. ", name, 3, LONG_NAME);
        utn_getFloat("Ingrese sueldo: ", "\Error. ", &salary, 3);
        utn_getInt("Ingrese sector de trabajo(1-2-3-4): ", "\nError. ", &sector, 3, 4, 1);
        if(addEmployees(list,QTY_EMPLOYEES,id,name,lastName,salary,sector,index)==0)
        {
            printf("\nEl ID para %s %s es: %d\n",list[index].lastName,list[index].name,list[index].id);
            list[index].isEmpty=FALSE;
            retorno=0;
        }
    }
    return retorno;
}

/* \brief generateNewId: Generates a new ID that's +1 from previous loaded employee ID.
 */

static int generateNewId(void)
{
	static int id;

	id = id+1;
	return id;
}

/* \brief addEmployees: add in a existing list of employees the values received
 *  as parameters in the first empty position.
 * \param sEmployee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int id: id generated by generateNewId() function
 * \param char name[]: Input by user
 * \param char lastName[]: Input by user
 * \param float salary: Input by user
 * \param int sector: Input by user
 * \return (-1) Error / (0) Ok
 */

static int addEmployees(sEmployee* list,int len,int id,char name[],char lastName[],float salary,int sector,int index)
{
    int retorno=0;
    list[index].id=id;
    strcpy(list[index].name,name);
    strcpy(list[index].lastName,lastName);
    list[index].salary=salary;
    list[index].sector=sector;
    return retorno;
}

/* \brief findEmployeeById: find an Employee by Id then returns the index position in array.
 * \param sEmployee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int index: Pointer to index of ID searched
 * \param int id: id to search
 * \return (-1) Error / (0) Ok
 */

int findEmployeeById(sEmployee* list, int len,int* index, int id)
{
	int retorno = -1;

	if (list != NULL && len > 0)
	{
		for (int i = 0; i < len; i++)
		{
			if(list[i].isEmpty == FALSE)
			{
				if(list[i].id == id)
				{
					*index = i;
					retorno = 0;
					break;
				}
			}
			else
			{
				printf("\nERROR, ID INEXISTENTE.\n");
				break;
			}
		}
	}
	return retorno;
}
/*
 * \brief modifyEmployee: Modifies the data of an Employee by given Id.
 * Allows to modify individual fields of the employee by a switch
 * \param sEmployee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int index:index of ID given
 * \param int id: id given
 * \return (-1) Error / (0) Ok
 */

int modifyEmployee(sEmployee* list, int len,int index, int id)
{
	int retorno = -1;
	int choosenOption;
	char answer;
	sEmployee bufferEmployee;

	if(	list != NULL &&	len>0 && index>=0 && index<len && list[index].isEmpty == FALSE)
	{
		do
		{
			printf("Empleado a modificar\n");
			printf("Apellido y Nombre: %s %s Sueldo: %.2f Sector: %d.\n", list[index].lastName,list[index].name,list[index].salary,list[index].sector);
			utn_getInt("\nQue campo desea modificar:"
						"\n 1-Apellido."
						"\n 2-Nombre."
						"\n 3-Sector."
						"\n 4-Salario."
						"\nOpcion:", "\nError.", &choosenOption, 3, 4, 1);
			switch(choosenOption)
			{
				case 1:
					utn_getString("\nApellido:","\nError. ",bufferEmployee.lastName,2,LONG_NAME);
					strcpy(list[index].lastName,bufferEmployee.lastName);
					break;
				case 2:
					utn_getString("\nNombre:","\nError. ",bufferEmployee.name,2,LONG_NAME);
					strcpy(list[index].name,bufferEmployee.name);
					break;
				case 3:
					utn_getInt("Sector de trabajo(1-2-3-4): ", "\nError. ", &bufferEmployee.sector, 3, 4, 1);
					list[index].sector=bufferEmployee.sector;
					break;
				case 4:
					utn_getFloat("Sueldo: ", "\Error. ", &bufferEmployee.salary, 3);
					list[index].salary=bufferEmployee.salary;
					break;
			}
			utn_getChar("¿Desea seguir modificando este ID?(Y/N)", "Error. ", &answer, 'Y', 'N', 3);
		}while(answer!='N');
		retorno = 0;
	}
	return retorno;
}

/* \brief removeEmployee:Remove a Employee by Id (put isEmpty Flag in TRUE)
 * \param sEmployee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int index:index of ID given
 * \param int id: id given
 * \return (-1) Error / (0) Ok
 */

int removeEmployee(sEmployee* list, int len,int index, int id)
{
	int retorno = -1;
	char answer;
	sEmployee bufferEmployee;

	if(	list != NULL && len>0 && index>=0 && index<len && list[index].isEmpty == FALSE)
	{
		printf("Empleado a eliminar\n");
		printf("Apellido y Nombre: %s %s Sueldo: %.2f Sector: %d.\n", list[index].lastName,list[index].name,list[index].salary,list[index].sector);
		utn_getChar("¿Desea eliminar este ID?(Y/N)", "Error. ", &answer, 'Y', 'N', 3);
		if(answer=='Y')
		{
			bufferEmployee.id = id;
			bufferEmployee.isEmpty = TRUE;
			list[index] = bufferEmployee;
			printf("REGISTRO DE EMPLEADO BORRADO CON EXITO.");
			retorno = 0;
		}
		else
		{
			printf("ERROR, NO SE PUEDO BORRAR EL REGISTRO .");
		}
	}
	return retorno;
}

/* \brief sortEmployees:Sort the elements in the array of employees, the argument order
 * indicate UP or DOWN order
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param itn order: [2] indicate UP - [1] indicate DOWN
 * \return int Return (-1) if Error [Invalid length or NULL pointer] - (0) if Ok
 */

int sortEmployees(sEmployee* list, int len, int order)
{
	int retorno = -1;
	int i;
	int sorted;
	sEmployee bufferEmployee;

	if(list!= NULL && len > 0)
	{
		switch(order)
		{
			case 1:
				do
				{
					sorted = TRUE;
					for(i = 0; i < (len - 1); i++)
					{
						if(strncmp(list[i].lastName, list[i + 1].lastName,LONG_NAME)>0 ||
						  (strncmp(list[i].lastName, list[i + 1].lastName,LONG_NAME)==0 &&
						   strncmp(list[i].name, list[i + 1].name,LONG_NAME)>0))
						{
							bufferEmployee = list[i];
							list[i] = list[i + 1];
							list[i + 1] = bufferEmployee;
							sorted = FALSE;
						}
					}
				}while(sorted == FALSE);
				do
				{
					sorted = TRUE;
					for(i = 0; i < (len - 1); i++)
					{
						if(list[i].sector > list[i + 1].sector)
						{
							bufferEmployee = list[i];
							list[i] = list[i + 1];
							list[i + 1] = bufferEmployee;
							sorted = FALSE;
						}
					}
				}while(sorted == FALSE);
				break;
			case 2:
				do
				{
					sorted = TRUE;
					for(i = 0; i < (len - 1); i++)
					{
						if(strncmp(list[i].lastName, list[i + 1].lastName,LONG_NAME)<0 ||
						  (strncmp(list[i].lastName, list[i + 1].lastName,LONG_NAME)==0 &&
						   strncmp(list[i].name, list[i + 1].name,LONG_NAME)<0))
						{
							bufferEmployee = list[i];
							list[i] = list[i + 1];
							list[i + 1] = bufferEmployee;
							sorted = FALSE;
						}
					}
				}while(sorted == FALSE);
				do
				{
					sorted = TRUE;
					for(i = 0; i < (len - 1); i++)
					{
						if(list[i].sector < list[i + 1].sector)
						{
							bufferEmployee = list[i];
							list[i] = list[i + 1];
							list[i + 1] = bufferEmployee;
							sorted = FALSE;
						}
					}
				}while(sorted == FALSE);
				break;
		}
		retorno = 0;
	}
	return retorno;
}

/* \brief print the content of employees array
 * \param sEmployee* list: Pointer to array of employees
 * \param int len: Array length
 * \return (-1) Error / (0) Ok*
 */
int printEmployees(sEmployee* list, int len)
{
	int retorno = -1;
	if(list != NULL && len  > 0)
	{
		for(int i=0;i< len ;i++)
		{
			if(list[i].isEmpty == FALSE)
			{
				printf(" Sector: %d ID: %d - Apellido y Nombre: %s %s\n",list[i].sector, list[i].id, list[i].lastName,list[i].name);
			}
		}
		retorno = 0;
	}
	return retorno;
}

